// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8NpHZP-WH9kfOpDfdqxiMXEMi7a5Ckbo',
    appId: '1:522253883024:web:b2b13010d583bbe94cea15',
    messagingSenderId: '522253883024',
    projectId: 'couple-expenses-2',
    authDomain: 'couple-expenses-2.firebaseapp.com',
    storageBucket: 'couple-expenses-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-qWotY52lMxQAitXw6bSk7nCfXM-eyE',
    appId: '1:522253883024:android:90bcf532dcdcfe6f4cea15',
    messagingSenderId: '522253883024',
    projectId: 'couple-expenses-2',
    storageBucket: 'couple-expenses-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd0M_Nd3NRcG0HVLjHztw8Bbjf29gdrKE',
    appId: '1:522253883024:ios:794b25a23fd0c0c14cea15',
    messagingSenderId: '522253883024',
    projectId: 'couple-expenses-2',
    storageBucket: 'couple-expenses-2.firebasestorage.app',
    iosBundleId: 'com.example.coupleExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd0M_Nd3NRcG0HVLjHztw8Bbjf29gdrKE',
    appId: '1:522253883024:ios:794b25a23fd0c0c14cea15',
    messagingSenderId: '522253883024',
    projectId: 'couple-expenses-2',
    storageBucket: 'couple-expenses-2.firebasestorage.app',
    iosBundleId: 'com.example.coupleExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8NpHZP-WH9kfOpDfdqxiMXEMi7a5Ckbo',
    appId: '1:522253883024:web:dd6bc8d49610571b4cea15',
    messagingSenderId: '522253883024',
    projectId: 'couple-expenses-2',
    authDomain: 'couple-expenses-2.firebaseapp.com',
    storageBucket: 'couple-expenses-2.firebasestorage.app',
  );
}
